### ISSUE TITLE
_opendistro index missing, unable to login, health-checks failing 

### ISSUE THREAD

**Issue by srajappa** [MaibornWolff/dcos-opendistro#2]
After setting up OpenDistro Elastic-search unit, with `service.security.transport_encryption.enabled` set to `false`, I am seeing the following error in the Kibana logs:

```
{"type":"log","@timestamp":"2020-02-04T22:59:30Z","tags":["listening","info"],"pid":13,"message":"Server running at http://0.0.0.0:5601"}
...
...
... <once I login through Kibana UI> 
{"type":"error","@timestamp":"2020-02-04T23:02:36Z","tags":[],"pid":13,"level":"error","error":{"message":"[index_not_found_exception] no such index [_opendistro], with { resource.type=\"index_expression\" & resource.id=\"_opendistro\" & index_uuid=\"_na_\" & index=\"_opendistro\" }","name":"Error","stack":"Error: [index_not_found_exception] no such index [_opendistro], with { resource.type=\"index_expression\" & resource.id=\"_opendistro\" & index_uuid=\"_na_\" & index=\"_opendistro\" }\n    at badImplementation (/opt/lib/mesos/slave/slaves/cf42e75a-9494-44f3-a6ea-31a7c4649ee0-S0/frameworks/586f1066-d290-41ec-991f-e233a5fafc62-0000/executors/infra_opendistro-kibana.instance-22d4f645-47a1-11ea-a3b5-70b3d5800001._app.1/runs/14d59a8f-ef08-4636-9b17-d73708be61b7/kibana-7.2.0-linux-x86_64/plugins/opendistro_security/lib/auth/types/basicauth/routes.js:153:36)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/v1/auth/login","path":"/api/v1/auth/login","href":"/api/v1/auth/login"},"message":"[index_not_found_exception] no such index [_opendistro], with { resource.type=\"index_expression\" & resource.id=\"_opendistro\" & index_uuid=\"_na_\" & index=\"_opendistro\" }"}
```

Also, I do have to mention, the health check is failing for Kibana even though the above message is reported in the logs. 

I am also adding the `options-kibana.json` file
```
{
    "kibana": {
        "elastic_url": "http://coordinator.infraopendistro.l4lb.thisdcos.directory:9200",
        "username_secret": "infra/opendistro-kibana/username",
        "password_secret": "infra/opendistro-kibana/password"
    },
    "service": {
        "name": "/infra/opendistro-kibana",
        "virtual_network_enabled": false,
        "virtual_network_name": "dcos"
    },
    "node": {
        "count": 1,
        "mem": 8192,
        "cpus": 1
    }
}
```
And `options-elastic.json` file:
```
{
    "data_nodes": {
        "count": 2,
        "cpus": 1,
        "disk": 10000,
        "disk_type": "ROOT",
        "heap": {
            "size": 1024
        },
        "mem": 2048
    },
    "elasticsearch": {
        "health_user": "admin",
        "health_user_password": "admin",
        "plugins": "",
        "opendistro_security_config_zip": "<LOCAL_S3>",
        "xpack_security_enabled": false
    },
    "coordinator_nodes": {
        "count": 1,
        "mem": 2048,
        "heap": {
            "size": 1024
        },
        "cpus": 1
    },
    "config_node": {
        "enabled": true
    },
    "service": {
        "name": "/infra/opendistro",
        "security": {
            "transport_encryption": {
                "enabled": false
            }
        },
        "service_account": "opendistro-principal",
        "service_account_secret": "/infra/opendistro/opendistro-secret",
        "virtual_network_enabled": true,
        "virtual_network_name": "dcos",
        "update_strategy": "serial"
    }
}
```

**Comment by swoehrl-mw** [comment]
Hi @srajappa ,
at the moment the kibana part of the framework is not designed to run without opendistro security (because I am mainly trying out opendistro for the security features so I did not yet get around to equiping kibana with the other opendistro parts or making it optional). So disabling security on the elastic side will very likely not work with the opendistro-kibana. If you want to use opendistro without security, for the moment I suggest using the "normal" kibana framework.

**Comment by srajappa** [comment]
Thanks @swoehrl-mw for your prompt reply. 

After understanding the error, even I in a desperation thought of using the **_normal_** `kibana` for the OpenDistro Elastic. 

May I know what parts are required in order to equip `Kibana` to work without security features ? I am assuming it has something to do with customizing `Kibana` from source code. 

CLOSING ISSUE

**Comment by swoehrl-mw** [comment]
To make the opendistro-kibana work without security at the moment https://github.com/MaibornWolff/dcos-opendistro/blob/master/kibana/files/kibana_setup.sh#L33 would need to be changed so that the step is done based on a configuration setting. At the moment it would then just be a vanilla kibana.

**Comment by srajappa** [comment]
Got it! 

I did make a change to `kibana_setup.sh`, I commented the line 33:

```
$MESOS_SANDBOX/kibana-$ELASTIC_VERSION-linux-x86_64/bin/kibana-plugin install file://$MESOS_SANDBOX/opendistro_security_kibana_plugin-${OPENDISTRO_SECURITY_VERSION}.zip
```
But I would see the following error:
`{"type":"log","@timestamp":"2020-02-04T16:49:02Z","tags":["fatal","root"],"pid":13,"message":"{ Error: \"opendistro_security.multitenancy.enabled\" setting was not applied. Check for spelling errors and ensure that expected plugins are installed.\n    at KbnServer._default (/opt/lib/mesos/slave/slaves/cf42e75a-9494-44f3-a6ea-31a7c4649ee0-S1/frameworks/586f1066-d290-41ec-991f-e233a5fafc62-0000/executors/infra_opendistro-kibana.instance-c5412713-476d-11ea-a3b5-70b3d5800001._app.4/runs/841b8925-e052-4e0e-92bc-f836652bb89b/kibana-7.2.0-linux-x86_64/src/legacy/server/config/complete.js:90:17) code: 'InvalidConfig', processExitCode: 64 }"}`

It appears to me that on running the `opendistro_security_kibana_plugin` it populates some keys which make it favorable to run the `kibana` binary. 

I just wanted to share with you my findings.

**Comment by srajappa** [comment]
Just an update, I was able to get Kibana package working without `opendistro` security plugin. 

Also, made a change in the `marathon.json.mustache` file, so that the health-check succeeds. 

PS: Would you like me to raise a Pull Request (PR), you can cherry pick the changes if you'd want.
